server:
  port: 8082
  servlet:
      context-path: /twitterxs
  error:
    whitelabel: 
      enabled: true

# expose all actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/twitterxs?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: 
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: none
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
  messages:
    use-code-as-default-message: true
  mvc:
   view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
 